source 'https://github.com/CocoaPods/Specs.git'

target 'TEArrayDiffCalculator_Example', :exclusive => true do
  pod "TEArrayDiffCalculator", :path => "../"
end

target 'TEArrayDiffCalculator_Tests', :exclusive => true do
  pod "TEArrayDiffCalculator", :path => "../"

  pod 'Kiwi'
end
